# Generated by Django 2.2.10 on 2020-03-03 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AestheticsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Tipo de serviço',
                'verbose_name_plural': 'Tipos de serviço',
            },
        ),
        migrations.CreateModel(
            name='BodyTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Tratamento de corpo',
                'verbose_name_plural': 'Tratamentos de corpo',
            },
        ),
        migrations.CreateModel(
            name='EpilationProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Epilação produto',
                'verbose_name_plural': 'Epilação produtos',
            },
        ),
        migrations.CreateModel(
            name='EpilationZones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Epilação zona',
                'verbose_name_plural': 'Epilação zonas',
            },
        ),
        migrations.CreateModel(
            name='ManicureColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Manicure cor',
                'verbose_name_plural': 'Manicure cores',
            },
        ),
        migrations.CreateModel(
            name='ManicureProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Manicure produto',
                'verbose_name_plural': 'Manicure produtos',
            },
        ),
        migrations.CreateModel(
            name='ManicureService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Manicure serviço',
                'verbose_name_plural': 'Manicure serviços',
            },
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Massagem',
                'verbose_name_plural': 'Massagens',
            },
        ),
        migrations.CreateModel(
            name='SkinType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Tipo de pele',
                'verbose_name_plural': 'Tipos de pele',
            },
        ),
        migrations.CreateModel(
            name='Aesthetics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('price', models.IntegerField(verbose_name='Valor do serviço')),
                ('record', models.TextField(blank=True, null=True, verbose_name='Registo')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('body_treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.BodyTreatment', verbose_name='Tratamentos de corpo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Client', verbose_name='Cliente')),
                ('epilation_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.EpilationProduct', verbose_name='Epilação produto')),
                ('epilation_zones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.EpilationZones', verbose_name='Epilação zonas tratadas')),
                ('manicure_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ManicureColor', verbose_name='Manicure cor')),
                ('manicure_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ManicureProduct', verbose_name='Manicure produto')),
                ('manicure_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ManicureService', verbose_name='Manicure serviço')),
                ('massage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Massage', verbose_name='Massagem')),
                ('pedicure_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedicure', to='core.ManicureColor', verbose_name='Pedicure cor')),
                ('pedicure_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedicure', to='core.ManicureProduct', verbose_name='Pedicure produto')),
                ('pedicure_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedicure', to='core.ManicureService', verbose_name='Pedicure serviço')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('skin_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.SkinType', verbose_name='Tipo de pele')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.AestheticsType', verbose_name='Tipo de serviço')),
            ],
            options={
                'verbose_name': 'Estética e Manicure',
                'verbose_name_plural': 'Estética e Manicure',
            },
        ),
    ]
