# Generated by Django 2.2.10 on 2021-01-02 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_aesthetics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Ondulação',
                'verbose_name_plural': 'Ondulação',
            },
        ),
        migrations.CreateModel(
            name='Gloss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Gloss',
                'verbose_name_plural': 'Gloss',
            },
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('price', models.IntegerField(verbose_name='Valor do serviço')),
                ('record', models.TextField(blank=True, null=True, verbose_name='Registo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Client', verbose_name='Cliente')),
                ('coloring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Coloring', verbose_name='Coloração')),
                ('curling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Curling', verbose_name='Ondulação')),
                ('gloss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Gloss', verbose_name='Gloss')),
                ('locks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Locks', verbose_name='Madeixas')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('straightening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Straightening', verbose_name='Alisamento')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
            },
        ),
    ]
